version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: optivus-postgres
    environment:
      POSTGRES_USER: optivus
      POSTGRES_PASSWORD: optivus_pass
      POSTGRES_DB: optivusdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - optivus-net

  redis:
    image: redis:7
    container_name: optivus-redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - optivus-net

  mongodb:
    image: mongo
    container_name: optivus-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    restart: always
    networks:
      - optivus-net

volumes:
  pgdata:
  mongodata:

networks:
  optivus-net:
    driver: bridge